/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : LCD1.c
**     Project     : Power Systems
**     Processor   : STM32F051
**     Component   : LCD
**     Version     : 2.0
**     Compiler    : MDK-ARM
**     Date/Time   : 2019-04-11
**     Abstract    :
**          This component implements a driver for 2x16 character displays.
**     Settings    :
**          Component name                                 : LCD1
**          HW Interface                                   : 
**            LCD Type                                     : generic
**            LCD Lines                                    : 2
**            Characters per Line                          : 16
**            Line Addresses                               : 
**              Line 1                                     : 00
**              Line 2                                     : 40
**              Line 3                                     : 10
**              Line 4                                     : 50
**            Read from Display                            : Disabled
**            Wait (us)                                    : 0
**            E signal                                     : CtrlPin
**            RS signal                                    : CtrlPin
**            Data/Control Bus                             : 
**              Data/Control Bus Width                     : 4bit
**              DB4..DB7                                   : Enabled
**     Contents    :
**         WriteLCDCommand  - void LCD1_WriteLCDCommand(uint8_t cmd);
**         Write            - void LCD1_Write(char ch);
**         WriteLn          - void LCD1_WriteLn(void);
**         WriteLineStr     - void LCD1_WriteLineStr(uint8_t line, char *str);
**         WriteString      - void LCD1_WriteString(char *str);
**         ShiftLeft        - void LCD1_ShiftLeft(void);
**         ShiftRight       - void LCD1_ShiftRight(void);
**         GotoXY           - void LCD1_GotoXY(uint8_t line, uint8_t column);
**         SetEntryMode     - void LCD1_SetEntryMode(bool increment, bool shiftLeft);
**         CursorShiftRight - void LCD1_CursorShiftRight(void);
**         CursorShiftLeft  - void LCD1_CursorShiftLeft(void);
**         Home             - void LCD1_Home(void);
**         Line             - void LCD1_Line(uint8_t line);
**         Clear            - void LCD1_Clear(void);
**         LCD1_DefineChars - void LCD1_DefineChars(void);
*
** ###################################################################*/
/*!
** @file LCD1.c
** @version 01.00
** @brief
**          This component implements a driver for multiple 2x16 character displays.
*/         
/*!
**  @addtogroup LCD1_module LCD1 module documentation
**  @{
*/         

/* MODULE LCD1. */

#include "Lcd_Alpha_16x2.h"
#include "main.h"



/* DEFINES for display commands.
   See
   - www.freescale.com/files/microcontrollers/doc/app_note/AN1745.pdf
   - http://www.mikrocontroller.net/articles/HD44780
   for additional details.
*/
#define ClearDisplayCmd                 0x01 /* clears the display */

#define ReturnHomeCmd                   0x02 /* moves the cursor to the beginning of the first line */

#define EntryModeSetCmd                 0x04
  #define EntryModeSet_ShiftOn             1 /* S flag: shift display */
  #define EntryModeSet_IncrementOn         2 /* I/D flag: increment cursor */

#define DisplayOnOffControlCmd          0x08 /* Display on/off control command. There are 3 bits D, C and B as well */
  #define DisplayOnOffControl_BlinkOn      1 /* B flag: blinking cursor on/off; B=1 blinking, B=0 not blinking */
  #define DisplayOnOffControl_CursorOn     2 /* C flag: cursor on/off, C=1 cursor on, C=0 cursor off */
  #define DisplayOnOffControl_DisplayOn    4 /* D flag: display on/off, D=1 display on, D=0 display off */

#define FunctionSetCmd                  0x20
  #define FunctionSet_8bit              0x10 /* DL flag: DL=1: 8bit, DL=0: 4bit */
  #define FunctionSet_4bit                 0 /* DL flag: DL=1: 8bit, DL=0: 4bit */
  #define FunctionSet_2Lines            0x08 /* N flag: number of display lines: N=1 2 or 4 lines, N=0 1 line */
  #define FunctionSet_1Line                0 /* N flag: number of display lines: N=1 2 or 4 lines, N=0 1 line */
  #define FunctionSet_Font5x10          0x04 /* F flag: character font, F=1 5x10 dots, F=0 5x8 dots */
  #define FunctionSet_Font5x8              0 /* F flag: character font, F=1 5x10 dots, F=0 5x8 dots */

#define SetCgramAddress                 0x48

#define CursorOnCmd    (DisplayOnOffControlCmd|DisplayOnOffControl_DisplayOn|DisplayOnOffControl_CursorOn)
#define CursorOffCmd   (DisplayOnOffControlCmd|DisplayOnOffControl_DisplayOn)
#define GotoXYCmd      0x80  /* 0x80 | Display RAM address */
#define Line1Offset    0x00 /* Display RAM address of first line, usually 0x00 */
#define Line2Offset    0x40 /* Display RAM address of second line, usually 0x40 */
#define Line3Offset    0x10 /* Display RAM address of third line, usually 0x10 */
#define Line4Offset    0x50 /* Display RAM address of fourth line, usually 0x50 */
#define FirstLineCmd   (GotoXYCmd|Line1Offset)
#define SecondLineCmd  (GotoXYCmd|Line2Offset)
#define ThirdLineCmd   (GotoXYCmd|Line3Offset)
#define FourthLineCmd  (GotoXYCmd|Line4Offset)

#define RightShiftCmd      0x1C
#define LeftShiftCmd       0x18
#define RightShiftCursor   0x14
#define LeftShiftCursor    0x10

#define BusyFlag       0x80 /* BF Flag */


/* support for custom soft characters in the display which can be used with LCD1_LoadSoftChar() */
const uint8_t LCD1_SoftCharUE[8] = { /* ü */
    0x11, 0x00, 0x11, 0x11, 0x11, 0x13, 0x0d, 0
/* X...X
   .....
   X...X
   X...X
   X...X
   X..XX
   .XX.X */
};

const uint8_t LCD1_SoftCharCedilla[8] = { /* ç */
    0x00, 0x00, 0x0E, 0x11, 0x10, 0x15, 0x0E, 0x10   //ç
/* .....
   .....    
   .XXX.
   X...X
   X....
   X.X.X
   .XXX.
   X.... */
};

const uint8_t LCD1_SoftCharAtil[8] = { /* ã */
    0x0D, 0x16, 0x0E, 0x01, 0x0F, 0x11, 0x0F, 0x00   //ã
/* .XX.X
   X.XX.
   .XXX.
   ....X
   .XXXX
   X...X
   .XXXX 
   ..... */ 
};

const uint8_t LCD1_SoftCharEagudo[8] = { /* é */
    0x02, 0x04, 0x0E, 0x11, 0x1F, 0x10, 0x0E, 0x00  //é
/* ...X.
   ..X..
   .XXX.
   X...X
   XXXXX
   X....
   .XXX. 
   ..... */ 
};

#define  MaxCgramChars     3    // Number of special chars in CGRAM


const uint8_t CGRAM [MaxCgramChars][8] = {0x00, 0x00, 0x0E, 0x11, 0x10, 0x15, 0x0E, 0x10,   //ç
                                          0x0D, 0x16, 0x0E, 0x01, 0x0F, 0x11, 0x0F, 0x00,   //ã
                                          0x02, 0x04, 0x0E, 0x11, 0x1F, 0x10, 0x0E, 0x00};  //é

/* macros for the RS pin */
#define ClrRS() \
        HAL_GPIO_WritePin(LCD_RS_GPIO_Port, LCD_RS_Pin, GPIO_PIN_RESET)       /* RS=0: command mode */
#define SetRS() \
        HAL_GPIO_WritePin(LCD_RS_GPIO_Port, LCD_RS_Pin, GPIO_PIN_SET)         /* RS=1: data mode */

/* macros for the EN pin */
#define ClrEN() \
        HAL_GPIO_WritePin(LCD_EN_GPIO_Port, LCD_EN_Pin, GPIO_PIN_RESET)       /* EN=0 */
#define SetEN() \
        HAL_GPIO_WritePin(LCD_EN_GPIO_Port, LCD_EN_Pin, GPIO_PIN_SET)         /* EN=1 */


/* waiting macros */
#define Waitns(x) \
        DelayNs(x)                 /* Wait x ns */
#define Waitus(x) \
        DelayNs((uint8_t)x*100)                 /* Wait x us */
#define Waitms(x) \
        osDelay(x)                 /* Wait x ms */

/* timings from Hitachi HD44708.pdf */
#define Timing_PWeh_ns   230 /* PWeh: Enable Pulse width (high level) */
//#define Timing_tAS_ns     40 /* tAB: Address set-up time (RS, RW to E ) */
//#define Timing_tDDR_ns   160 /* tDDR: Data delay time */
//#define Timing_tCYCLE_ns 500 /* tCYLE: Enable Cycle time */

#define LCD1_WAIT_DISPLAY_US                       0 /* wait time as specified in properties */
#define LCD1_WAIT_LCD_CMD_AFTER_4BIT_DATA1_US     15 /* wait time after first 4bit data */
#define LCD1_WAIT_LCD_CMD_AFTER_4BIT_DATA2_US     60 /* wait time after second 4bit data */


static void DataPut(uint8_t val) {
//  HAL_GPIO_WritePin(LCD_D4_GPIO_Port,  (LCD_D4_Pin | LCD_D5_Pin | LCD_D6_Pin | LCD_D7_Pin) & ( val<<4)       , GPIO_PIN_SET);
//  HAL_GPIO_WritePin(LCD_D4_GPIO_Port, ((LCD_D4_Pin | LCD_D5_Pin | LCD_D6_Pin | LCD_D7_Pin) & (~val<<4)) << 16, GPIO_PIN_SET);

  HAL_GPIO_WritePin(LCD_D7_GPIO_Port, LCD_D7_Pin, (val&(1<<3))!=0 ? GPIO_PIN_SET : GPIO_PIN_RESET);
  HAL_GPIO_WritePin(LCD_D6_GPIO_Port, LCD_D6_Pin, (val&(1<<2))!=0 ? GPIO_PIN_SET : GPIO_PIN_RESET);
  HAL_GPIO_WritePin(LCD_D5_GPIO_Port, LCD_D5_Pin, (val&(1<<1))!=0 ? GPIO_PIN_SET : GPIO_PIN_RESET);
  HAL_GPIO_WritePin(LCD_D4_GPIO_Port, LCD_D4_Pin, (val&(1<<0))!=0 ? GPIO_PIN_SET : GPIO_PIN_RESET);
}

/* Internal method prototypes */

static void DelayNs(uint16_t time)
{
    uint16_t x;
    for (x = 0; x < time; x++) {}
}

/*
** ===================================================================
**     Method      :  EnablePulse (component LCDHTA)
**
**     Description :
**         Creates a pulse to transfer data and/or commands
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static void EnablePulse(void)
{
    SetEN();
    Waitns(Timing_PWeh_ns);
    ClrEN();                              /* set to 0 to finish pulse */
}


/*
** ===================================================================
**     Method      :  LCD1_WriteLCDCommand (component LCDHTA)
**     Description :
**         Writes a command to the display
**     Parameters  :
**         NAME            - DESCRIPTION
**         cmd             - command passed to the LCD
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_WriteLCDCommand(uint8_t cmd)
{
#if LCD1_WAIT_DISPLAY_US > 0
    WAIT1_Waitus(LCD1_WAIT_DISPLAY_US);   /* wait for some time not to write to the display while he may be busy with previous command */
#endif
  /* 2 4bit transfer */
    DataPut((uint8_t)((cmd&0xF0)>>4));       /* Write the data (cycle #1) */
    EnablePulse();                        /* transfer data */
    Waitus(LCD1_WAIT_LCD_CMD_AFTER_4BIT_DATA1_US);
    DataPut((uint8_t)(cmd&0x0F) );           /* Write the data (cycle #2) */
    EnablePulse();                        /* do the command transfer */
    Waitus(LCD1_WAIT_LCD_CMD_AFTER_4BIT_DATA2_US);
}

/*
** ===================================================================
**     Method      :  LCD1_Clear (component LCDHTA)
**     Description :
**         Clears the display and moves the cursor to the first line.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_Clear(void)
{
    LCD1_WriteLCDCommand(ClearDisplayCmd); /* send the clear command to the LCD */
}

/*
** ===================================================================
**     Method      :  LCD1_Home (component LCDHTA)
**     Description :
**         Moves the cursor to the beginning of the first line.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_Home(void)
{
    LCD1_WriteLCDCommand(ReturnHomeCmd);  /* moves the cursor to the beginning of the first line */
}

/*
** ===================================================================
**     Method      :  LCD1_WriteLCDData (component LCDHTA)
**
**     Description :
**         Writes data to the display
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void LCD1_WriteLCDData(uint8_t ch)
{
#if LCD1_WAIT_DISPLAY_US > 0
   WAIT1_Waitus(LCD1_WAIT_DISPLAY_US);  /* wait for some time not to write to the display while he may be busy with previous command */
#endif
   SetRS();                             /* RS = 1: data mode */
   /* 2 4bit transfer */
   DataPut((uint8_t)((ch&0xF0)>>4));       /* Write the data (cycle #1) */
   EnablePulse();                       /* transfer data */
   Waitus(LCD1_WAIT_LCD_CMD_AFTER_4BIT_DATA1_US);
   DataPut((uint8_t)(ch&0x0F));            /* Write the data (cycle #2) */
   EnablePulse();                       /* do the command transfer */
   Waitus(LCD1_WAIT_LCD_CMD_AFTER_4BIT_DATA2_US);
   ClrRS();                             /* RS = 0: back to command mode */
}

/*
** ===================================================================
**     Method      :  LCD1_GotoXY (component LCDHTA)
**     Description :
**         Places the cursor on a specified position on the display.
**     Parameters  :
**         NAME            - DESCRIPTION
**         line            - Line number starting with 1
**         column          - Column number starting with 1
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_GotoXY(uint8_t line, uint8_t column)
{
/* row is in the range 1..LCD_Nof_Lines and column in the range 1..LCD_Nof_Columns */
    LCD1_WriteLCDCommand((uint8_t)(GotoXYCmd + (column-1) + (line==1 ? 0x00:Line2Offset)));
}

/*
** ===================================================================
**     Method      :  LCD1_ShiftLeft (component LCDHTA)
**     Description :
**         Shifts all characters to the left.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_ShiftLeft(void)
{
    LCD1_WriteLCDCommand(LeftShiftCmd);
}

/*
** ===================================================================
**     Method      :  LCD1_Write (component LCDHTA)
**     Description :
**         Write a single character to the display
**     Parameters  :
**         NAME            - DESCRIPTION
**         ch              - Character to write
**     Returns     : Nothing
** ===================================================================
*/
/* The method is implemented as a macro, see LCD1.h */
/*
** ===================================================================
**     Method      :  LCD1_WriteLn (component LCDHTA)
**     Description :
**         Writes a new line to the display
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_WriteLn(void)
{
    LCD1_WriteLCDCommand(SecondLineCmd);
}

/*
** ===================================================================
**     Method      :  LCD1_WriteString (component LCDHTA)
**     Description :
**         Writes a string to the display at the current cursor
**         position.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * str             - Pointer to string (zero byte terminated)
**                           to write to the display
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_WriteString(char *str)
{
    while (*str != '\0')
    {
        LCD1_Write(*str);
        str++;
    }
}

/*
** ===================================================================
**     Method      :  LCD1_WriteLineStr (component LCDHTA)
**     Description :
**         Writes a full line to the display (clears the rest of the
**         line).
**     Parameters  :
**         NAME            - DESCRIPTION
**         line            - Line number (starting with 1).
**       * str             - Pointer to the string which should be
**                           shown on the display.
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_WriteLineStr(uint8_t line, char *str)
{
    uint8_t i;

    LCD1_Line(line);                      /* select line */
    for(i = 0; i < LCD1_MAX_LCD_LINE_CHARS && *str!='\0'; i++, str++) 
    {
        LCD1_Write(*str);
    }
  /* Clear the rest of the line */
    for (; i < LCD1_MAX_LCD_LINE_CHARS; i++) 
    {
        LCD1_Write(' ');
    }
}

/*
** ===================================================================
**     Method      :  LCD1_Line (component LCDHTA)
**     Description :
**         Sets the current line.
**     Parameters  :
**         NAME            - DESCRIPTION
**         line            - Line number, starting with 1
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_Line(uint8_t line)
{
    LCD1_WriteLCDCommand((uint8_t)(line==1?FirstLineCmd:SecondLineCmd));
}

/*
** ===================================================================
**     Method      :  LCD1_DefineChars (component LCDHTA)
**     Description :
**         Defines special user characters on CGRAM
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_DefineChars(void)
{
	uint8_t i, j;

	
	LCD1_WriteLCDCommand(SetCgramAddress); // Set address of first CGRAM character 

	for (i = 0; i < MaxCgramChars; i ++)
	    for (j = 0; j < 8; j ++)
        {
            LCD1_WriteLCDData(CGRAM[i][j]);
        }
}

/*
** ===================================================================
**     Method      :  LCD1_Init (component LCDHTA)
**
**     Description :
**         Display driver initialization routine.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void LCD1_Init(void)
{
  /* This function initializes the driver.
     The low level init already shall have set our data port to input/output, currently set to output,
     plus all control pins are set as outputs with low values. To be sure, we do it here again. */
    ClrEN();                              /* EN Pin low */
    ClrRS();                              /* RS Pin low: command mode */
	
    DataPut(0);

  /* send the reset sequence according to the data sheet */
    Waitms(80);                           /* wait for more than 15ms after Vcc rises to 4.5V, wait for more than 40ms after Vcc rises to 2.7V. In case of POR (Power On Reset) we need some additional time. */
    DataPut(0x3);                         /* BF cannot be checked before this function, function set (interface is 8bits long) */
    EnablePulse();                        /* transfer data */
    Waitms(5);                            /* wait for more than 4.1 ms */
  /* 0x3 is already on the bus from previous DataPut(), do not need to put it again here */
    EnablePulse();                        /* transfer data */
    Waitus(100);                          /* wait for more than 100us */
  /* 0x3 is already on the bus from previous DataPut(), do not need to put it again here */
    EnablePulse();                        /* transfer data */
    Waitus(100);                          /* wait for more than 100us */

    DataPut(0x2);                         /* Function set */
    EnablePulse();                        /* transfer data */
    Waitus(100);

    LCD1_WriteLCDCommand(FunctionSetCmd|FunctionSet_Font5x8
                 |FunctionSet_4bit      /* we are using 4bit data bus */ \
                 |FunctionSet_2Lines    /* we are using two or more lines */
                 );

    LCD1_WriteLCDCommand(DisplayOnOffControlCmd|DisplayOnOffControl_DisplayOn);
    LCD1_WriteLCDCommand(ClearDisplayCmd); /* Clear display */
    LCD1_WriteLCDCommand(EntryModeSetCmd|EntryModeSet_IncrementOn); /* Entry mode set: Increment mode, display shift off */
    
    LCD1_DefineChars();      // Store special chars in CGRAM area
}

/*
** ===================================================================
**     Method      :  LCD1_ShiftRight (component LCDHTA)
**     Description :
**         Shifts all characters to the right.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_ShiftRight(void)
{
    LCD1_WriteLCDCommand(RightShiftCmd);
}

/*
** ===================================================================
**     Method      :  LCD1_SetEntryMode (component LCDHTA)
**     Description :
**         Configures the display entry mode, if the cursor has to
**         shift and/or if the display shall shift content while
**         displaying text.
**     Parameters  :
**         NAME            - DESCRIPTION
**         increment       - Increments (TRUE) or
**                           decrements (FALSE) the display address by 1
**                           when a character code is written into or
**                           read from DDRAM. The cursor or blinking
**                           moves to the right when incremented by 1
**                           and to the left when decremented by 1.
**         shiftLeft       - The display does not shift if
**                           the 'shift' is FALSE. If 'shift' is TRUE,
**                           it will seem as if the cursor does not move
**                           but the display does.
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_SetEntryMode(uint8_t increment, uint8_t shiftLeft)
{
    uint8_t flags = 0;

    if (increment) 
    {
        flags |= EntryModeSet_IncrementOn;
    }
    if (shiftLeft) 
    {
        flags |= EntryModeSet_ShiftOn;
    }
    LCD1_WriteLCDCommand((uint8_t)(EntryModeSetCmd|flags)); /* Entry mode set: Increment mode, display shift mode */
}

/*
** ===================================================================
**     Method      :  LCD1_CursorShiftRight (component LCDHTA)
**     Description :
**         Shift the cursor to the right.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_CursorShiftRight(void)
{
    LCD1_WriteLCDCommand(RightShiftCursor);
}

/*
** ===================================================================
**     Method      :  LCD1_CursorShiftLeft (component LCDHTA)
**     Description :
**         Shift the cursor to the left.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void LCD1_CursorShiftLeft(void)
{
    LCD1_WriteLCDCommand(LeftShiftCursor);
}

/* END LCD1. */

/*!
** @}
*/
/*
** ###################################################################
*/
